=== Seface-Studios/fogger/fogpack.schema.v1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "GenericConfiguration": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string",
          "pattern": "^#([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$",
          "description": "Hexadecimal value of the color to be applied.",
          "default": "#FF00FF"
        }
      },

      "required": ["color"]
    },

    "FogConfiguration": {
      "allOf": [
        { "$ref": "#/definitions/GenericConfiguration" },
        {
          "type": "object",
          "properties": {
            "distance": {
              "type": "integer",
              "description": "The distance (in chunks) the fog will be in relation to the player. This option has the same Render Distance logic, the difference is that it will only be applicable to fog.",
              "default": 16,
              "minimum": 2,
              "maximum": 32
            }
          }
        }
      ]
    }
  },

  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "description": "The Fogpack version."
    },

    "name": {
      "type": "string",
      "description": "The Fogpack name."
    },

    "identifier": {
      "type": "string",
      "description": "The Fogpack identifier. This identifier must be unique and in the format 'namespace:identifier'.",
      "default": "namespace:identifier",
      "pattern": "^(?:(?:(?!minecraft|minecon|fogger))+[a-z]*:[a-z_]*)+$"
    },

    "description": {
      "type": "string",
      "description": "The Fogpack description."
    },

    "authors": {
      "type": "array",
      "description": "Everyone involved in setting up this Fogpack.",
      "items": [
        { "type": "string" }
      ]
    },

    "config": {
      "type": "object",
      "description": "All the Fogpack configuration.",
      "properties": {
        "sky": {
          "$ref": "#/definitions/GenericConfiguration",
          "description": "Sky configuration."
        },

        "fog": {
          "$ref": "#/definitions/FogConfiguration",
          "description": "Fog configuration."
        },

        "water": {
          "$ref": "#/definitions/GenericConfiguration",
          "description": "Water configuration."
        },

        "water_fog": {
          "$ref": "#/definitions/GenericConfiguration",
          "description": "Water fog configuration."
        }
      }
    }
  },

  "required": ["version", "name", "identifier", "description", "authors", "config"]
}

=== Seface-Studios/fogger/src/main/resources/assets/fogger/fogpacks/miami_vibes.fogpack.json
{
  "$schema": "../../../../../../fogpack.schema.v1.json",
  "version": "1.0.0",
  "name": "Miami Vibes",
  "identifier": "seface:miami_vibes",
  "description": "",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#FE7678"
    },

    "fog": {
      "color": "#FE608E"
    }
  }
}

=== Seface-Studios/fogger/src/main/resources/fogpacks/swamp_lands.fogpack.json
{
  "$schema": "https://www.sefacestudios.net/fogpack.schema.v1.json",
  "version": "1.0.0",
  "name": "Swamp Lands",
  "identifier": "seface:swamp_lands",
  "description": "What are you doing in my swamp?!",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#ABD2C8"
    },

    "fog": {
      "color": "#67917A"
    }
  }
}

=== Seface-Studios/fogger/src/main/resources/fogpacks/elden_ring.fogpack.json
{
  "$schema": "https://www.sefacestudios.net/fogpack.schema.v1.json",
  "version": "1.0.1",
  "name": "Elden Ring",
  "identifier": "seface:elden_ring",
  "description": "I am the warrior jar known as Alexander. Iron Fist Alexander, in fact.",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#E7EBB5"
    },

    "fog": {
      "color": "#FFD879"
    },

    "clouds": {
      "color": "#FFD879"
    }
  }
}

=== Seface-Studios/fogger/src/main/resources/assets/fogger/fogpacks/blue_world.fogpack.json
{
  "$schema": "../../fogpack.schema.v1.json",
  "version": "1.0.0",
  "name": "Blue World",
  "identifier": "seface:blue_world",
  "description": "",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#095473"
    },

    "fog": {
      "distance": 16,
      "color": "#5B95AA"
    }
  }
}

=== Seface-Studios/fogger/src/main/resources/fogpacks/miami_vibes.fogpack.json
{
  "$schema": "https://www.sefacestudios.net/fogpack.schema.v1.json",
  "version": "1.0.0",
  "name": "Miami Vibes",
  "identifier": "seface:miami_vibes",
  "description": "Lucia... Do you know why you're here? - Bad luck, I guess.",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#FE7678"
    },

    "fog": {
      "color": "#FE608E"
    }
  }
}

=== Seface-Studios/fogger/src/main/resources/assets/fogger/fogpacks/elden_ring.fogpack.json
{
  "$schema": "../../fogpack.schema.v1.json",
  "version": "1.0.0",
  "name": "Elden Ring",
  "identifier": "seface:elden_ring",
  "description": "",
  "authors": ["Seface Studios"],

  "config": {
    "sky": {
      "color": "#E7EBB5"
    },

    "fog": {
      "distance": 16,
      "color": "#FFD879"
    }
  }
}
